[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nia"
version = "0.1.0"
description = "A self-reflective, adaptive, and evolving multi-agent system"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
dependencies = [
    "qdrant-client",  # For vector storage
    "numpy",
    "openai",  # For embeddings
    "aiohttp",  # For async HTTP
    "pydantic",  # For data validation
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "black",
    "isort",
    "mypy",
]

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
multi_line_output = 3
