services:
  neo4j:
    build:
      context: ./neo4j
      dockerfile: Dockerfile
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ../data/neo4j/data:/data
      - ../data/neo4j/logs:/logs
      - ../data/neo4j/import:/import
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_config_strict__validation_enabled=false
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=false
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    build:
      context: ./qdrant
      dockerfile: Dockerfile
    ports:
      - "6333:6333"  # HTTP
      - "6334:6334"  # GRPC
    volumes:
      - ../data/qdrant:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://localhost:6333/collections > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
